// Re-export workspace module — persistence is directory-only (no separate DB file).
export {
  WORKSPACE_DIR,
  PLANE_FILE,
  NOTIFY_FILE,
  LLM_CONTEXT_FILE,
  AGENTS_DIR,
  PROVIDERS_FILE,
  newId,
  nowIso,
  ensureWorkspace as ensureDataFile,
  readBoard,
  writeBoard,
  updateBoard,
  normalizeBoard,
  normalizeElement,
  mergeElement,
  writeCardMarkdown,
  getWorkspaceDir,
  setWorkspaceDir,
  touchWorkspaceNotify,
  readLlmContext,
  consumeLlmContext,
  appendLlmContext,
  replaceLlmContext,
  clearLlmContext,
  readChat,
  appendChatMessage,
  readProviders,
  writeProviders
} from "./workspace.js";
